### ISSUE TITLE
Embed block cannot be nested within another embed block without named block wrapper

### ISSUE THREAD

**Issue by ESKempken** [twig-component-tools/tct-bundle#2] opened 2022-07-06 10:04 UTC
When we are working with default blocks, we still need to wrap it in a named block tag, eg TComponent_default. 

Current working usage:
```
<TComponent>
  {% block TComponent_default %}
    <MComponent>
      <h1>Foo</h1>
      <p>Boo hoo</p>
    </MComponent>
  {% endblock %}
</TComponent>
```
 
Desired usage:
```
<TComponent>  
  <MComponent>  
    <h1>Foo</h1>  
    <p>Boo hoo</p>  
  </MComponent>  
</TComponent>
```

> A template that extends another one cannot include content outside Twig blocks. Did you forget to put the content inside a {% block %} tag?

**Comment by barthy-koeln** [comment] 2022-07-08 09:31
```twig
{# file: TOuter.twig #}
<div style="padding-left: 1rem;">
  <h1>TOuter Title</h1>
  <div>
    {% block TOuter_default %}{% endblock %}
  </div>
</div>
```

```twig
{# file: TInner.twig #}
<div style="padding-left: 1rem; border-left: 1px solid black;">
  <h2>TInner Title</h2>
  {% block TInner_default %}{% endblock %}
</div>
```

```twig
{# file: test.twig #}
<TOuter>
  <p>Outer Text</p>

  <TInner>
    <p>Inner Text</p>
  </TInner>
</TOuter>

<hr>

<TOuter>
  <p>Outer Text</p>

  <TInner>
    <p>Inner Text</p>

    <TOuter>
      <p>Nested Outer Text</p>

      <TInner>
        <p>Nested Inner Text</p>
      </TInner>
    </TOuter>
  </TInner>
</TOuter>
```

Output:

![tct_test](https://user-images.githubusercontent.com/10552683/177962862-4b8ecd72-4579-4b9f-9c88-c10e94376e9c.png)

____


I cannot reproduce the issue with the current `main` branch. Am I missing anything?

**Comment by barthy-koeln** [comment] 2022-07-22 07:37
Closing because this has been tried and tested.

**Closed as completed by barthy-koeln** 2022-07-22 07:37 UTC
Labels: enhancement
